### ISSUE TITLE
API call again forbidden

### ISSUE THREAD

**Issue by UnclePhil** [derhuerst/flightradar24-client#34] opened 2023-07-16 11:10 UTC
RAAAH !!!
Code installed 7 days ago, and from yesterday (14/07/23) it's again "forbidden". 
But they change the detection method.
If I change the user agent i'm still dropped in NodeRed, but if i take a browser with the same public IP , it's ok.
Investigating.

**Comment by tux2000** [comment] 2023-07-16 11:13
as of right now its still working for me... with flightradar24-client@1.0.0

**Comment by efraespada** [comment] 2023-07-16 12:19
Not for me with a simple local test.

```
Error: Forbidden
statusCode: 403
```

The problem is the current `UserAgent`:

```js
const headers = {
	//'User-Agent': 'https://github.com/derhuerst/fetch-flightradar24-flights'
}
```

It could be banned.

I've replaced that piece of code with:

```js
const headers = {
	'User-Agent': makeId(5)
}

function makeId(length) {
	let result = '';
	const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
	const charactersLength = characters.length;
	let counter = 0;
	while (counter < length) {
		result += characters.charAt(Math.floor(Math.random() * charactersLength));
		counter += 1;
	}
	return result;
}
```

**Comment by tux2000** [comment] 2023-07-16 12:37
@efraespada, did you test with version 1.0.0? The user agent should be fixed already using the code here: https://github.com/derhuerst/flightradar24-client/blob/abc2a54a747cb1153ec97fe5df91541bd163ea0d/lib/random-user-agent.js (see also #29 )

**Comment by efraespada** [comment] 2023-07-16 12:39
Sorry, you are right 😄 

Now working as expected 🚀

**Comment by UnclePhil** [comment] 2023-07-16 14:08
I ll check that this evening.

Le dim. 16 juil. 2023, 14:39, Efra Espada ***@***.***> a
écrit :

**Comment by UnclePhil** [comment] 2023-07-16 16:47
My version is correct, and i have the problem

the package.json in the node_modules
```
{
	"name": "flightradar24-client",
	"description": "Fetch aircraft data from Flightradar24.",
	"version": "1.0.0",
	"type": "module",
	"main": "index.js",
	"files": [
		"index.js",
		"lib"
	],
	"keywords": [
		"aviation",
		"airplanes",
		"flights",
		"flightradar24"
	],
	"author": "Jannis R <mail@jannisr.de>",
	"contributors": [
		"@E3V3A"
	],
	"homepage": "https://github.com/derhuerst/flightradar24-client",
	"repository": "derhuerst/flightradar24-client",
	"bugs": "https://github.com/derhuerst/flightradar24-client/issues",
	"license": "ISC",
	"engines": {
		"node": ">=18"
	},
	"dependencies": {
		"fetch-ponyfill": "^7.1.0",
		"moment-timezone": "^0.5.13",
		"parse-jsonp": "^2.0.0"
	},
	"devDependencies": {
		"eslint": "^8.44.0",
		"tap-min": "^2.0.0",
		"tape": "^5.6.4"
	},
	"scripts": {
		"lint": "eslint .",
		"test": "node test.js | tap-min",
		"prepublishOnly": "npm run lint && npm test"
	}
}

```

**Comment by tux2000** [comment] 2023-07-16 17:01
Probably this is obvious for everyone else, but when trying to understand what was wrong on my system, I figured out that the flightradar24-client module was installed not only in the top level `node_modules` folder but as an older version in the `node_modules/node-red-contrib-fr24tube/node_modules` folder. I know your the author of fr24tube, so its unlikely that this would get in your way, but still letting you know, just in case...

**Comment by UnclePhil** [comment] 2023-07-16 17:07
I ve Just see  the same thing.

I love node but i hate npm.....

I ll check that asap

**Comment by derhuerst** [comment] 2023-07-18 08:29
Just to prevent false positives here, can you all make sure you're running the latest `0.x` version (`0.3.1`) or `1.x` (currently `1.0.0`)? You can check this using `npm ls` (or `npm ls --depth 2`, if `flightradar24-client` is nested within another package's dependencies).

In addition, it might be that you're being IP-rate-limited or -blocked. To rule this out, you can try to debug this from a fresh IP (that you haven't made requests from).

**Comment by derhuerst** [comment] 2023-09-18 09:49
Closing this. Please try to provide steps to reproduce the issue when it occurs again.

**Closed as completed by derhuerst** 2023-09-18 09:49 UTC
Labels: question
